# Generated by Django 4.2.7 on 2023-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0002_category_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('MN', 'Mens_clothing'), ('WN', 'Womens_clothing'), ('BC', 'Babys_clothing'), ('SH', 'Shirts'), ('JE', 'Jeans'), ('SW', 'Swimwear'), ('SL', 'Sleeping_wear'), ('SP', 'Sportswear'), ('JP', 'Jumpsuits'), ('BL', 'Blazers'), ('JK', 'Jackets'), ('SH', 'Shoes')], max_length=2),
        ),
    ]
