# Generated by Django 4.2 on 2025-03-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0003_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='colorVariation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='sizeVariation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
