# Generated by Django 4.2 on 2025-03-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0004_cart_colorvariation_cart_sizevariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='isPaid',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eshopping.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_size_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshopping.productsizecolor'),
        ),
    ]
