# Generated by Django 4.2 on 2025-03-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0006_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPaid', models.FloatField(default=0)),
                ('transactionId', models.CharField(max_length=255)),
                ('transactionDate', models.DateField(null=True)),
                ('receiptNumber', models.CharField(max_length=255, null=True)),
                ('referencePhoneNumber', models.CharField(max_length=255, null=True)),
                ('resultDesc', models.CharField(max_length=255, null=True)),
                ('resultCode', models.CharField(max_length=255, null=True)),
                ('responseReceived', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='Mpesa', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopping.order')),
            ],
        ),
    ]
