# Generated by Django 4.2 on 2025-02-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0008_remove_customer_username_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshopping.products'),
        ),
    ]
