# Generated by Django 4.2 on 2025-03-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshopping', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles'),
        ),
    ]
